name: Assignment_nodejs

on:
  push:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx (required for Docker Compose)
        uses: docker/setup-buildx-action@v2
        
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Compose Services
        run: |
          docker-compose build
          docker-compose push

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            # Navigate to the project directory
            cd /home/ubuntu/

            # Clone or pull the latest code from GitHub
            if [ ! -d "Assignment_nodejs/.git" ]; then
            git clone git@github.com:fazil2915/Assignment_nodejs.git 
            else
            git pull origin main
            fi

            # Docker login to pull images from Docker Hub
            cd /home/ubuntu/Assignment_nodejs
            echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            # Stop and remove existing containers
            sudo docker-compose down || true

            # Pull the latest images
            sudo docker-compose pull

            # Start up the services
            sudo docker-compose up -d
    

            
