name: Assignment_nodejs

on:
  push:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run:  docker build -t fazilrahman9846/nodejs-app ./Backend --file ./Backend/Dockerfile

      - name: Publish image to Docker Hub
        run: docker push fazilrahman9846/nodejs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker-compose pull
            docker-compose up -d